_G.pets_exp = {
	[0] = 0,
	[1] = 1,
	[2] = 1000,
	[3] = 1000,
	[4] = 1000,
	[5] = 1000,
	[6] = 1500,
	[7] = 1500,
	[8] = 2000,
	[9] = 2000,
	[10] = 2500,
}
pets_shop = {
	pet_change = { price = {don = 500}, type = "pet_change" },
	feed_x230 = { price = { don = 3, rp = 15 }, give = 230, type ="feed" },
	feed_x600 = { price = { don = 7, rp = 35 }, give = 600, type ="feed" },
}
pets_list = {
	[1] = {
		[1] = {name = "ratingpoints_1", price = {rp = 250}, itemname = "spell_item_pet_RDA_simple_1", rarity = "#afeeee", text_color = "#afeeee", type = "pet", currency = "mmrpoints", tier = 1},
		[2] = {name = "ratingpoints_2", price = {rp = 350}, itemname = "spell_item_pet_RDA_simple_2", rarity = "#afeeee", text_color = "#afeeee", type = "pet", currency = "mmrpoints", tier = 1},
		[3] = {name = "ratingpoints_3", price = {rp = 450}, itemname = "spell_item_pet_RDA_simple_3", rarity = "#afeeee", text_color = "#afeeee", type = "pet", currency = "mmrpoints", tier = 1},
	},
	[2] = {
		[1] = {name = "pet_15", price = {rp = 550}, itemname = "spell_item_pet_RDA_mana_regen", rarity = "#0044ff", text_color = "#0044ff", type = "pet", tier = 2},
		[2] = {name = "pet_13", price = {rp = 550}, itemname = "spell_item_pet_RDA_hp_com", rarity = "#0044ff", text_color = "#0044ff", type = "pet", tier = 2},
		[3] = {name = "pet_14", price = {rp = 550}, itemname = "spell_item_pet_RDA_dmg_com", rarity = "#0044ff", text_color = "#0044ff", type = "pet", tier = 2},
	},
	[3] = {
		[1] = {name = "pet_5", price = {don = 100}, itemname = "spell_item_pet_RDA_total_dmg", rarity = "#800080", text_color = "#800080", type = "pet", tier = 3},
		[2] = {name = "pet_6", price = {don = 100}, itemname = "spell_item_pet_RDA_int", rarity = "#800080", text_color = "#800080", type = "pet", tier = 3},
		[3] = {name = "pet_7", price = {don = 100}, itemname = "spell_item_pet_RDA_str", rarity = "#800080", text_color = "#800080", type = "pet", tier = 3},
		[4] = {name = "pet_8", price = {don = 100}, itemname = "spell_item_pet_RDA_agi", rarity = "#800080", text_color = "#800080", type = "pet", tier = 3},
		[5] = {name = "pet_9", price = {don = 100}, itemname = "spell_item_pet_RDA_heal", rarity = "#800080", text_color = "#800080", type = "pet", tier = 3},
	},
	[4] = {
		[1] = {name = "pet_1", price = {don = 150}, itemname = "spell_item_pet_RDA_dmg", rarity = "#ee82ee", text_color = "#ee82ee", type = "pet", tier = 4},
		[2] = {name = "pet_2", price = {don = 150}, itemname = "spell_item_pet_RDA_hp", rarity = "#ee82ee", text_color = "#ee82ee", type = "pet", tier = 4},
		[3] = {name = "pet_3", price = {don = 150}, itemname = "spell_item_pet_RDA_fast", rarity = "#ee82ee", text_color = "#ee82ee", type = "pet", tier = 4},
		[4] = {name = "pet_4", price = {don = 150}, itemname = "spell_item_pet_RDA_cleave", rarity = "#ee82ee", text_color = "#ee82ee", type = "pet", tier = 4},
		[5] = {name = "pet_10", price = {don = 150}, itemname = "spell_item_pet_RDA_block", rarity = "#ee82ee", text_color = "#ee82ee", type = "pet", tier = 4},
		[6] = {name = "pet_11", price = {don = 150}, itemname = "spell_item_pet_RDA_all_dmg_amp", rarity = "#ee82ee", text_color = "#ee82ee", type = "pet", tier = 4},
		[7] = {name = "pet_12", price = {don = 150}, itemname = "spell_item_pet_RDA_gold", rarity = "#ee82ee", text_color = "#ee82ee", type = "pet", tier = 4},
	},
	[5] = {
		[1] = {name = "pet_16", price = {don = 250}, itemname = "spell_item_pet_RDA_250_gold_and_exp", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[2] = {name = "pet_17", price = {don = 250}, itemname = "spell_item_pet_RDA_250_attribute_bonus", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[3] = {name = "pet_18", price = {don = 250}, itemname = "spell_item_pet_RDA_250_dmg_reduction", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[4] = {name = "pet_19", price = {don = 250}, itemname = "spell_item_pet_RDA_250_regen", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[5] = {name = "pet_20", price = {don = 250}, itemname = "spell_item_pet_RDA_250_bkb", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[6] = {name = "pet_21", price = {don = 250}, itemname = "spell_item_pet_RDA_250_phys_dmg_reducrion", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[7] = {name = "pet_22", price = {don = 250}, itemname = "spell_item_pet_RDA_250_pure_damage", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[8] = {name = "pet_23", price = {don = 250}, itemname = "spell_item_pet_RDA_250_no_spell_phys_bonus", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[9] = {name = "pet_24", price = {don = 250}, itemname = "spell_item_pet_RDA_250_no_phys_spell_bonus", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[10] = {name = "pet_25", price = {don = 250}, itemname = "spell_item_pet_RDA_250_minus_armor", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
	},
	[6] = {},
	[7] = {
		[1] = {name = "rosh_1", price = {}, itemname = "spell_item_pet_rda_roshan_1", rarity = "#ffa500", text_color = "#ffa500", type = "pet", tier = 7},
		[2] = {name = "rosh_2", price = {}, itemname = "spell_item_pet_rda_roshan_2", rarity = "#ffa500", text_color = "#ffa500", type = "pet", tier = 7},
	},
}
battle_pass_shop = {
	bp_premium = { price = {don = 150} },
	bp_experience = { price = { rp = 1000, don = 50}, give = 1000 },
}
_G.basicshop = {
	[1] = {
		name = "pets",
		[1] = {name = "pet_change", price = {don = 500}, image = "images/custom_game/RDAShop/items/pet_change.png", rarity = "#fa3535", text_color = "white", type = "pet_change", tooltip = "shop_image_pet_change_tooltip"},
		[2] = {name = "ratingpoints_1", price = {rp = 250}, itemname = "spell_item_pet_RDA_simple_1", rarity = "#00ff48", text_color = "#00ff48", type = "pet", currency = "mmrpoints", tier = 1},
		[3] = {name = "ratingpoints_2", price = {rp = 350}, itemname = "spell_item_pet_RDA_simple_2", rarity = "#00ff48", text_color = "#00ff48", type = "pet", currency = "mmrpoints", tier = 1},
		[4] = {name = "ratingpoints_3", price = {rp = 450}, itemname = "spell_item_pet_RDA_simple_3", rarity = "#00ff48", text_color = "#00ff48", type = "pet", currency = "mmrpoints", tier = 1},
		[5] = {name = "pet_15", price = {rp = 550}, itemname = "spell_item_pet_RDA_mana_regen", rarity = "#0044ff", text_color = "#0044ff", type = "pet", tier = 2},
		[6] = {name = "pet_13", price = {rp = 550}, itemname = "spell_item_pet_RDA_hp_com", rarity = "#0044ff", text_color = "#0044ff", type = "pet", tier = 2},
		[7] = {name = "pet_14", price = {rp = 550}, itemname = "spell_item_pet_RDA_dmg_com", rarity = "#0044ff", text_color = "#0044ff", type = "pet", tier = 2},
		[8] = {name = "pet_5", price = {don = 100}, itemname = "spell_item_pet_RDA_total_dmg", rarity = "#ffa600", text_color = "#ffa600", type = "pet", tier = 3},
		[9] = {name = "pet_6", price = {don = 100}, itemname = "spell_item_pet_RDA_int", rarity = "#ffa600", text_color = "#ffa600", type = "pet", tier = 3},
		[10] = {name = "pet_7", price = {don = 100}, itemname = "spell_item_pet_RDA_str", rarity = "#ffa600", text_color = "#ffa600", type = "pet", tier = 3},
		[11] = {name = "pet_8", price = {don = 100}, itemname = "spell_item_pet_RDA_agi", rarity = "#ffa600", text_color = "#ffa600", type = "pet", tier = 3},
		[12] = {name = "pet_9", price = {don = 100}, itemname = "spell_item_pet_RDA_heal", rarity = "#ffa600", text_color = "#ffa600", type = "pet", tier = 3},
		[13] = {name = "pet_1", price = {don = 150}, itemname = "spell_item_pet_RDA_dmg", rarity = "#d400ff", text_color = "#d400ff", type = "pet", tier = 4},
		[14] = {name = "pet_2", price = {don = 150}, itemname = "spell_item_pet_RDA_hp", rarity = "#d400ff", text_color = "#d400ff", type = "pet", tier = 4},
		[15] = {name = "pet_3", price = {don = 150}, itemname = "spell_item_pet_RDA_fast", rarity = "#d400ff", text_color = "#d400ff", type = "pet", tier = 4},
		[16] = {name = "pet_4", price = {don = 150}, itemname = "spell_item_pet_RDA_cleave", rarity = "#d400ff", text_color = "#d400ff", type = "pet", tier = 4},
		[17] = {name = "pet_10", price = {don = 150}, itemname = "spell_item_pet_RDA_block", rarity = "#d400ff", text_color = "#d400ff", type = "pet", tier = 4},
		[18] = {name = "pet_11", price = {don = 150}, itemname = "spell_item_pet_RDA_all_dmg_amp", rarity = "#d400ff", text_color = "#d400ff", type = "pet", tier = 4},
		[19] = {name = "pet_12", price = {don = 150}, itemname = "spell_item_pet_RDA_gold", rarity = "#d400ff", text_color = "#d400ff", type = "pet", tier = 4},
		[20] = {name = "pet_16", price = {don = 250}, itemname = "spell_item_pet_RDA_250_gold_and_exp", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[21] = {name = "pet_17", price = {don = 250}, itemname = "spell_item_pet_RDA_250_attribute_bonus", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[22] = {name = "pet_18", price = {don = 250}, itemname = "spell_item_pet_RDA_250_dmg_reduction", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[23] = {name = "pet_19", price = {don = 250}, itemname = "spell_item_pet_RDA_250_regen", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[24] = {name = "pet_20", price = {don = 250}, itemname = "spell_item_pet_RDA_250_bkb", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[25] = {name = "pet_21", price = {don = 250}, itemname = "spell_item_pet_RDA_250_phys_dmg_reducrion", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[26] = {name = "pet_22", price = {don = 250}, itemname = "spell_item_pet_RDA_250_pure_damage", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[27] = {name = "pet_23", price = {don = 250}, itemname = "spell_item_pet_RDA_250_no_spell_phys_bonus", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[28] = {name = "pet_24", price = {don = 250}, itemname = "spell_item_pet_RDA_250_no_phys_spell_bonus", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[29] = {name = "pet_25", price = {don = 250}, itemname = "spell_item_pet_RDA_250_minus_armor", rarity = "#fa3535", text_color = "#fa3535", type = "pet", tier = 5},
		[30] = {name = "feed_x230", price = {don = 3, rp = 15}, image = "images/custom_game/pet/shop_feed.png", give = 230, rarity = "#fa3535", text_color = "#fa3535", type ="feed", combinable = true, tooltip = "feed_x230_tooltip"},
		[31] = {name = "feed_x600", price = {don = 7, rp = 35}, image = "images/custom_game/pet/shop_feed.png", give = 600, rarity = "#fa3535", text_color = "#fa3535", type ="feed", combinable = true, tooltip = "feed_x600_tooltip"},
	},
	[2] = {
		name = "consumables",
		[1] = {name = "hot_offer", price = {don = 60}, rarity = "gold", type = "sale", counter = false, image = "images/custom_game/RDAShop/items/sale2.png", tooltip = "hot_offer_tooltip", package_contents = { item_armor_aura = 1, item_base_damage_aura = 1, item_expiriance_aura = 1, item_move_aura = 1, item_attack_speed_aura = 1, item_hp_aura = 1, item_ticket = 3, item_str = 1, item_agi = 1, item_int = 1, item_tree_gold = 1, item_forever_ward = 1, } },
		[2] = {name = "scroll_1", price = {don = 5}, itemname = "item_armor_aura", rarity = "gold", type = "consumabl", combinable = true, layout = "RDAShopItem2", counter = true},
		[3] = {name = "scroll_2", price = {don = 5}, itemname = "item_base_damage_aura", rarity = "gold", type = "consumabl", combinable = true, layout = "RDAShopItem2", counter = true},
		[4] = {name = "scroll_3", price = {don = 5}, itemname = "item_expiriance_aura", rarity = "gold", type = "consumabl", combinable = true, layout = "RDAShopItem2", counter = true},
		[5] = {name = "scroll_4", price = {don = 5}, itemname = "item_move_aura", rarity = "gold", type = "consumabl", combinable = true, layout = "RDAShopItem2", counter = true},
		[6] = {name = "scroll_5", price = {don = 5}, itemname = "item_attack_speed_aura", rarity = "gold", type = "consumabl", combinable = true, layout = "RDAShopItem2", counter = true},
		[7] = {name = "scroll_6", price = {don = 5}, itemname = "item_hp_aura", rarity = "gold", type = "consumabl", combinable = true, layout = "RDAShopItem2", counter = true},
		[8] = {name = "scroll_13", price = {don = 5}, itemname = "item_book_mage_damage", rarity = "gold", type = "consumabl", combinable = true, layout = "RDAShopItem2", counter = true},
		[9] = {name = "scroll_14", price = {don = 5}, itemname = "item_book_phys_damage", rarity = "gold", type = "consumabl", combinable = true, layout = "RDAShopItem2", counter = true},
		[10] = {name = "scroll_15", price = {don = 5}, itemname = "item_book_gold", rarity = "gold", type = "consumabl", combinable = true, layout = "RDAShopItem2", counter = true},
		[11] = {name = "scroll_11", price = {don = 2}, itemname = "item_ticket", rarity = "gold", type = "consumabl", combinable = true, layout = "RDAShopItem2", counter = true},
		[12] = {name = "scroll_12", price = {don = 10}, itemname = "item_boss_summon", rarity = "gold", type = "consumabl", combinable = true, layout = "RDAShopItem2", counter = true},
		[13] = {name = "other_1", price = {don = 5}, itemname = "item_str", rarity = "red", layout = "RDAShopItem1"},
		[14] = {name = "other_2", price = {don = 5}, itemname = "item_agi", rarity = "green", layout = "RDAShopItem1"},
		[15] = {name = "other_3", price = {don = 5}, itemname = "item_int", rarity = "blue", layout = "RDAShopItem1"},
		[16] = {name = "other_4", price = {don = 15}, itemname = "item_tree_gold", rarity = "gold", layout = "RDAShopItem1"},
		[17] = {name = "other_8", price = {don = 30}, itemname = "item_tower_protection", rarity = "gold", layout = "RDAShopItem1"},
		[18] = {name = "other_49", price = {don = 25}, itemname = "item_forever_ward", rarity = "gold", type = "consumabl", combinable = true, layout = "RDAShopItem2", counter = true},
	},
	[3] = {
		name = "effects",
		[1] = {name = "effect_7", price = {don = 10}, rarity = "white", image = "images/custom_game/RDAShop/items/ef7.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[2] = {name = "effect_8", price = {don = 10}, rarity = "white", image = "images/custom_game/RDAShop/items/ef8.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[3] = {name = "effect_23", price = {don = 10}, rarity = "white", image = "images/custom_game/RDAShop/items/ef23.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[4] = {name = "effect_24", price = {don = 10}, rarity = "white", image = "images/custom_game/RDAShop/items/ef24.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[5] = {name = "effect_22", price = {don = 10}, rarity = "white", image = "images/custom_game/RDAShop/items/ef22.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[6] = {name = "effect_9", price = {don = 10}, rarity = "white", image = "images/custom_game/RDAShop/items/ef9.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[7] = {name = "effect_10", price = {don = 10}, rarity = "white", image = "images/custom_game/RDAShop/items/ef10.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[8] = {name = "effect_13", price = {don = 10}, rarity = "white", image = "images/custom_game/RDAShop/items/ef13.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[9] = {name = "effect_14", price = {don = 10}, rarity = "white", image = "images/custom_game/RDAShop/items/ef14.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[10] = {name = "effect_15", price = {don = 10}, rarity = "white", image = "images/custom_game/RDAShop/items/ef15.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[11] = {name = "effect_6", price = {don = 10}, rarity = "white", image = "images/custom_game/RDAShop/items/ef6.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[12] = {name = "effect_11", price = {don = 15}, rarity = "white", image = "images/custom_game/RDAShop/items/ef11.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[13] = {name = "effect_18", price = {don = 15}, rarity = "white", image = "images/custom_game/RDAShop/items/ef18.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[14] = {name = "effect_19", price = {don = 15}, rarity = "white", image = "images/custom_game/RDAShop/items/ef19.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[15] = {name = "effect_20", price = {don = 15}, rarity = "white", image = "images/custom_game/RDAShop/items/ef20.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[16] = {name = "effect_21", price = {don = 15}, rarity = "white", image = "images/custom_game/RDAShop/items/ef21.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[17] = {name = "effect_1", price = {don = 25}, rarity = "white", image = "images/custom_game/RDAShop/items/ef1.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[18] = {name = "effect_12", price = {don = 25}, rarity = "white", image = "images/custom_game/RDAShop/items/ef12.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[19] = {name = "effect_16", price = {don = 25}, rarity = "white", image = "images/custom_game/RDAShop/items/ef16.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[20] = {name = "effect_17", price = {don = 25}, rarity = "white", image = "images/custom_game/RDAShop/items/ef17.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[21] = {name = "effect_2", price = {don = 25}, rarity = "white", image = "images/custom_game/RDAShop/items/ef2.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[22] = {name = "effect_3", price = {don = 25}, rarity = "white", image = "images/custom_game/RDAShop/items/ef3.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[23] = {name = "effect_4", price = {don = 25}, rarity = "white", image = "images/custom_game/RDAShop/items/ef4.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
		[24] = {name = "effect_5", price = {don = 25}, rarity = "white", image = "images/custom_game/RDAShop/items/ef5.png", type = "effect", tooltip = "shop_image_effect_tooltip"},
	},
	[4] = {
		name = "spray",
		[1] = {name = "treasurie1_spray1", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/1.png", spray_path = "particles/spray/1.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[2] = {name = "treasurie1_spray2", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/2.png", spray_path = "particles/spray/2.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[3] = {name = "treasurie1_spray3", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/3.png", spray_path = "particles/spray/3.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[4] = {name = "treasurie1_spray4", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/4.png", spray_path = "particles/spray/4.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[5] = {name = "treasurie1_spray5", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/5.png", spray_path = "particles/spray/5.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[6] = {name = "treasurie1_spray6", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/6.png", spray_path = "particles/spray/6.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[7] = {name = "treasurie1_spray7", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/7.png", spray_path = "particles/spray/7.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[8] = {name = "treasurie1_spray8", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/8.png", spray_path = "particles/spray/8.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[9] = {name = "treasurie1_spray9", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/9.png", spray_path = "particles/spray/9.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[10] = {name = "treasurie1_spray10", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/10.png", spray_path = "particles/spray/10.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[11] = {name = "treasurie1_spray11", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/11.png", spray_path = "particles/spray/11.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[12] = {name = "treasurie1_spray12", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/12.png", spray_path = "particles/spray/12.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[13] = {name = "treasurie1_spray13", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/13.png", spray_path = "particles/spray/13.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[14] = {name = "treasurie1_spray14", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/14.png", spray_path = "particles/spray/14.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[15] = {name = "treasurie1_spray15", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/15.png", spray_path = "particles/spray/15.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie1" }},
		[16] = {name = "gems_reward_500", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/gems_reward_500.png", hidden = true, source = { treasury = "treasurie1", main_prize = true }},
		------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
		[17] = {name = "treasurie2_spray1", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/17.png", spray_path = "particles/spray/17.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[18] = {name = "treasurie2_spray2", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/18.png", spray_path = "particles/spray/18.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[19] = {name = "treasurie2_spray3", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/19.png", spray_path = "particles/spray/19.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[20] = {name = "treasurie2_spray4", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/20.png", spray_path = "particles/spray/20.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[21] = {name = "treasurie2_spray5", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/21.png", spray_path = "particles/spray/21.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[22] = {name = "treasurie2_spray6", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/22.png", spray_path = "particles/spray/22.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[23] = {name = "treasurie2_spray7", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/23.png", spray_path = "particles/spray/23.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[24] = {name = "treasurie2_spray8", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/24.png", spray_path = "particles/spray/24.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[25] = {name = "treasurie2_spray9", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/25.png", spray_path = "particles/spray/25.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[26] = {name = "treasurie2_spray10", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/26.png", spray_path = "particles/spray/26.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[27] = {name = "treasurie2_spray11", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/27.png", spray_path = "particles/spray/27.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[28] = {name = "treasurie2_spray12", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/28.png", spray_path = "particles/spray/28.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[29] = {name = "treasurie2_spray13", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/29.png", spray_path = "particles/spray/29.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[30] = {name = "treasurie2_spray14", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/30.png", spray_path = "particles/spray/30.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[31] = {name = "treasurie2_spray15", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/31.png", spray_path = "particles/spray/31.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie2" }},
		[32] = {name = "gems_reward_500", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/gems_reward_500.png", hidden = true, source = { treasury = "treasurie2", main_prize = true }},
		------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
		[33] = {name = "treasurie3_spray1", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/33.png", spray_path = "particles/spray/33.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[34] = {name = "treasurie3_spray2", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/34.png", spray_path = "particles/spray/34.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[35] = {name = "treasurie3_spray3", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/35.png", spray_path = "particles/spray/35.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[36] = {name = "treasurie3_spray4", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/36.png", spray_path = "particles/spray/36.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[37] = {name = "treasurie3_spray5", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/37.png", spray_path = "particles/spray/37.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[38] = {name = "treasurie3_spray6", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/38.png", spray_path = "particles/spray/38.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[39] = {name = "treasurie3_spray7", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/39.png", spray_path = "particles/spray/39.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[40] = {name = "treasurie3_spray8", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/40.png", spray_path = "particles/spray/40.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[41] = {name = "treasurie3_spray9", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/41.png", spray_path = "particles/spray/41.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[42] = {name = "treasurie3_spray10", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/42.png", spray_path = "particles/spray/42.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[43] = {name = "treasurie3_spray11", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/43.png", spray_path = "particles/spray/43.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[44] = {name = "treasurie3_spray12", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/44.png", spray_path = "particles/spray/44.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[45] = {name = "treasurie3_spray13", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/45.png", spray_path = "particles/spray/45.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[46] = {name = "treasurie3_spray14", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/46.png", spray_path = "particles/spray/46.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[47] = {name = "treasurie3_spray15", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/47.png", spray_path = "particles/spray/47.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie3" }},
		[48] = {name = "gems_reward_500", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/gems_reward_500.png", hidden = true, source = { treasury = "treasurie3", main_prize = true }},
		------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
		[49] = {name = "treasurie4_spray1", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/48.png", spray_path = "particles/spray/48.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie4" }},
		[50] = {name = "treasurie4_spray2", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/49.png", spray_path = "particles/spray/49.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie4" }},
		[51] = {name = "treasurie4_spray3", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/50.png", spray_path = "particles/spray/50.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie4" }},
		[52] = {name = "treasurie4_spray4", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/51.png", spray_path = "particles/spray/51.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie4" }},
		[53] = {name = "treasurie4_spray5", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/52.png", spray_path = "particles/spray/52.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie4" }},
		[54] = {name = "treasurie4_spray6", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/53.png", spray_path = "particles/spray/53.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie4" }},
		[55] = {name = "treasurie4_spray7", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/54.png", spray_path = "particles/spray/54.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie4" }},
		[56] = {name = "treasurie4_spray8", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/55.png", spray_path = "particles/spray/55.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie4" }},
		[57] = {name = "treasurie4_spray9", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/56.png", spray_path = "particles/spray/56.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie4" }},
		[58] = {name = "treasurie4_spray10", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/57.png", spray_path = "particles/spray/57.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie4" }},
		[59] = {name = "treasurie4_spray11", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/58.png", spray_path = "particles/spray/58.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie4" }},
		[60] = {name = "treasurie4_spray12", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/59.png", spray_path = "particles/spray/59.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie4" }},
		[61] = {name = "rp_reward_1000", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/rp_reward_1000.png", hidden = true, source = { treasury = "treasurie4", main_prize = true }},
		[62] = {name = "gems_reward_50", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/gems_reward_50.png", hidden = true, source = { treasury = "treasurie4", main_prize = true }},
		[63] = {name = "gems_reward_500", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/gems_reward_500.png", hidden = true, source = { treasury = "treasurie4", main_prize = true }},
		[64] = {name = "roshan_reward_1", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/roshan_reward_1.png", hidden = true, source = { treasury = "treasurie4", main_prize = true }},
		------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
		[65] = {name = "treasurie5_spray1", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/60.png", spray_path = "particles/spray/60.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie5" }},
		[66] = {name = "treasurie5_spray2", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/61.png", spray_path = "particles/spray/61.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie5" }},
		[67] = {name = "treasurie5_spray3", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/62.png", spray_path = "particles/spray/62.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie5" }},
		[68] = {name = "treasurie5_spray4", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/63.png", spray_path = "particles/spray/63.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie5" }},
		[69] = {name = "treasurie5_spray5", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/64.png", spray_path = "particles/spray/64.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie5" }},
		[70] = {name = "treasurie5_spray6", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/65.png", spray_path = "particles/spray/65.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie5" }},
		[71] = {name = "treasurie5_spray7", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/66.png", spray_path = "particles/spray/66.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie5" }},
		[72] = {name = "treasurie5_spray8", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/67.png", spray_path = "particles/spray/67.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie5" }},
		[73] = {name = "treasurie5_spray9", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/68.png", spray_path = "particles/spray/68.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie5" }},
		[74] = {name = "treasurie5_spray10", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/69.png", spray_path = "particles/spray/69.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie5" }},
		[75] = {name = "treasurie5_spray11", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/70.png", spray_path = "particles/spray/70.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie5" }},
		[76] = {name = "treasurie5_spray12", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/71.png", spray_path = "particles/spray/71.vpcf", type = "spray", tooltip = "shop_image_spray_tooltip", counter = false, source = { treasury = "treasurie5" }},
		[77] = {name = "rp_reward_1500", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/rp_reward_1500.png", hidden = true, source = { treasury = "treasurie5", main_prize = true }},
		[78] = {name = "gems_reward_75", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/gems_reward_75.png", hidden = true, source = { treasury = "treasurie5", main_prize = true }},
		[79] = {name = "gems_reward_750", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/gems_reward_750.png", hidden = true, source = { treasury = "treasurie5", main_prize = true }},
		[80] = {name = "roshan_reward_2", price = {}, rarity = "white", image = "images/custom_game/RDAShop/spray/roshan_reward_2.png", hidden = true, source = { treasury = "treasurie5", main_prize = true }},
		
	},
	[5] = {
		name = "treasuries",
		[1] = {name = "treasurie1", price = {don = 2, rp = 75}, rarity = "white", image = "images/custom_game/RDAShop/treasuries/1.png", type = "treasuries", tooltip = "", combinable = true, counter = true, layout = "RDAShopItem2", compensation = 15, treasure_main_reward = { gems_reward_500 = 0.1 } },
		[2] = {name = "treasurie2", price = {don = 2, rp = 75}, rarity = "white", image = "images/custom_game/RDAShop/treasuries/2.png", type = "treasuries", tooltip = "", combinable = true, counter = true, layout = "RDAShopItem2", compensation = 15, treasure_main_reward = { gems_reward_500 = 0.1 } },
		[3] = {name = "treasurie3", price = {don = 2, rp = 75}, rarity = "white", image = "images/custom_game/RDAShop/treasuries/3.png", type = "treasuries", tooltip = "", combinable = true, counter = true, layout = "RDAShopItem2", compensation = 15, treasure_main_reward = { gems_reward_500 = 0.1 } },
		[4] = {name = "treasurie4", price = {don = 5, rp = 1000}, rarity = "white", image = "images/custom_game/RDAShop/treasuries/4.png", type = "treasuries", tooltip = "", combinable = true, counter = true, layout = "RDAShopItem2", compensation = 0, treasure_main_reward = { rp_reward_1000 = 6, gems_reward_50 = 4, gems_reward_500 = 0.5, roshan_reward_1 = 0.15 } }, --1496, для 1200 - 0.2
		[5] = {name = "treasurie5", price = {don = 8, rp = 1500}, rarity = "white", image = "images/custom_game/RDAShop/treasuries/5.png", type = "treasuries", tooltip = "", combinable = true, counter = true, layout = "RDAShopItem2", compensation = 0, treasure_main_reward = { rp_reward_1500 = 6, gems_reward_75 = 4, gems_reward_750 = 0.5, roshan_reward_2 = 0.15 } }, --2490, для 2000 - 0.18
	},
	-- [6] = {
	-- 	name = "other",
	-- 	[1] =  {name = "other_10", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/Axe.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_axe",tooltip="shop_image_heros_tooltip"},
	-- 	[2] =  {name = "other_11", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/bb.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_bristleback",tooltip="shop_image_heros_tooltip"},
	-- 	[3] =  {name = "other_12", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/cent.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_centaur",tooltip="shop_image_heros_tooltip"},
	-- 	[4] =  {name = "other_13", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/dk.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_dragon_knight",tooltip="shop_image_heros_tooltip"},
	-- 	[5] =  {name = "other_14", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/io.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_wisp",tooltip="shop_image_heros_tooltip"},
	-- 	[6] =  {name = "other_15", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/mars.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_mars",tooltip="shop_image_heros_tooltip"},
	-- 	[7] =  {name = "other_16", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/sk.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_sand_king",tooltip="shop_image_heros_tooltip"},
	-- 	[8] =  {name = "other_17", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/sven.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_sven",tooltip="shop_image_heros_tooltip"},
	-- 	[9] =  {name = "other_18", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/trent.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_treant",tooltip="shop_image_heros_tooltip"},
	-- 	[10] = {name = "other_19", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/wk.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_skeleton_king",tooltip="shop_image_heros_tooltip"},
	-- 	[11] = {name = "other_20", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/arc.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_arc_warden",tooltip="shop_image_heros_tooltip"},
	-- 	[12] = {name = "other_21", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/drowjpg.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_drow_ranger",tooltip="shop_image_heros_tooltip"},
	-- 	[13] = {name = "other_22", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/jugg.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_juggernaut",tooltip="shop_image_heros_tooltip"},
	-- 	[14] = {name = "other_23", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/luna.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_luna",tooltip="shop_image_heros_tooltip"},
	-- 	[15] = {name = "other_24", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/pa.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_phantom_assassin",tooltip="shop_image_heros_tooltip"},
	-- 	[16] = {name = "other_25", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/sf.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_nevermore",tooltip="shop_image_heros_tooltip"},
	-- 	[17] = {name = "other_26", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/slark.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_slark",tooltip="shop_image_heros_tooltip"},
	-- 	[18] = {name = "other_27", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/sniper.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_sniper",tooltip="shop_image_heros_tooltip"},
	-- 	[19] = {name = "other_28", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/spectre.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_spectre",tooltip="shop_image_heros_tooltip"},
	-- 	[20] = {name = "other_29", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/terror.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_terrorblade",tooltip="shop_image_heros_tooltip"},
	-- 	[21] = {name = "other_30", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/dazzle.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_dazzle",tooltip="shop_image_heros_tooltip"},
	-- 	[22] = {name = "other_31", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/lina.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_lina",tooltip="shop_image_heros_tooltip"},
	-- 	[23] = {name = "other_32", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/encha.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_enchantress",tooltip="shop_image_heros_tooltip"},
	-- 	[24] = {name = "other_33", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/lion.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_lion",tooltip="shop_image_heros_tooltip"},
	-- 	[25] = {name = "other_34", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/pugna.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_pugna",tooltip="shop_image_heros_tooltip"},
	-- 	[26] = {name = "other_35", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/ss.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_shadow_shaman",tooltip="shop_image_heros_tooltip"},
	-- 	[27] = {name = "other_36", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/tinker.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_tinker",tooltip="shop_image_heros_tooltip"},
	-- 	[28] = {name = "other_37", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/werlock.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_warlock",tooltip="shop_image_heros_tooltip"},
	-- 	[29] = {name = "other_38", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/wr.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_windrunner",tooltip="shop_image_heros_tooltip"},
	-- 	[30] = {name = "other_39", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/zeus.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_zuus",tooltip="shop_image_heros_tooltip"},
	-- 	[31] = {name = "other_40", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/demusa.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_medusa",tooltip="shop_image_heros_tooltip"},
	-- 	[32] = {name = "other_41", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/sky.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_skywrath_mage",tooltip="shop_image_heros_tooltip"},
	-- 	[33] = {name = "other_42", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/legion.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_legion_commander",tooltip="shop_image_heros_tooltip"},
	-- 	[34] = {name = "other_43", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/pudge.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_pudge",tooltip="shop_image_heros_tooltip"},
	-- 	[35] = {name = "other_44", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/marci.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_marci",tooltip="shop_image_heros_tooltip"},
	-- 	[36] = {name = "other_45", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/cm.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_crystal_maiden",tooltip="shop_image_heros_tooltip"},
	-- 	[37] = {name = "other_46", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/troll.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_troll_warlord",tooltip="shop_image_heros_tooltip"},
	-- 	[38] = {name = "other_47", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/techies.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_techies",tooltip="shop_image_heros_tooltip"},
	-- 	[39] = {name = "other_48", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/alchemist.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_alchemist",tooltip="shop_image_heros_tooltip"},
	-- 	[40] = {name = "other_50", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/bs.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_bloodseeker",tooltip="shop_image_heros_tooltip"},
	-- 	[41] = {name = "other_51", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/gr.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_gyrocopter",tooltip="shop_image_heros_tooltip"},
	-- 	[42] = {name = "other_52", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/aa.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_ancient_apparition",tooltip="shop_image_heros_tooltip"},
	-- 	[43] = {name = "other_53", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/magnus.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_magnataur",tooltip="shop_image_heros_tooltip"},
	-- 	[44] = {name = "other_54", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/huskar.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_huskar",tooltip="shop_image_heros_tooltip"},
	-- 	[45] = {name = "other_55", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/broodmother.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_broodmother",tooltip="shop_image_heros_tooltip"},
	-- 	[46] = {name = "other_56", price = {don = 200, rp = 1000}, image = "images/custom_game/RDAShop/heros/silencer.png", rarity = "gold", type = "talant", hero = "npc_dota_hero_silencer",tooltip="shop_image_heros_tooltip"},
	-- },
	[6] = {
		name = "gems",
		[1] = {name = "shop_gem_purple_puck_1", price = {don = 3, rp = 100}, image = "images/custom_game/RDAShop/gems/purple__1.png", rarity = "white", text_color = "white", type = "gem", give = 1000, gem_type = 1, combinable = true, tooltip="shop_image_gems_tooltip_1"},
		[2] = {name = "shop_gem_blue_puck_1", price = {don = 3, rp = 100}, image = "images/custom_game/RDAShop/gems/blue__1.png", rarity = "white", text_color = "white", type = "gem", give = 1000, gem_type = 2, combinable = true, tooltip="shop_image_gems_tooltip_2"},
		[3] = {name = "shop_gem_orange_puck_1", price = {don = 3, rp = 100}, image = "images/custom_game/RDAShop/gems/yellow__1.png", rarity = "white", text_color = "white", type = "gem", give = 1000, gem_type = 3, combinable = true, tooltip="shop_image_gems_tooltip_3"},
		[4] = {name = "shop_gem_red_puck_1", price = {don = 3, rp = 100}, image = "images/custom_game/RDAShop/gems/red__1.png", rarity = "white", text_color = "white", type = "gem", give = 1000, gem_type = 4, combinable = true, tooltip="shop_image_gems_tooltip_4"},
		[5] = {name = "shop_gem_green_puck_1", price = {don = 3, rp = 100}, image = "images/custom_game/RDAShop/gems/green__1.png", rarity = "white", text_color = "white", type = "gem", give = 1000, gem_type = 5, combinable = true, tooltip="shop_image_gems_tooltip_5"},
		[6] = {name = "shop_gem_purple_puck_2", price = {don = 10, rp = 200}, image = "images/custom_game/RDAShop/gems/purple__2.png", rarity = "white", text_color = "white", type = "gem", give = 4000, gem_type = 1, combinable = true, tooltip="shop_image_gems_tooltip_1"},
		[7] = {name = "shop_gem_blue_puck_2", price = {don =10, rp = 200}, image = "images/custom_game/RDAShop/gems/blue__2.png", rarity = "white", text_color = "white", type = "gem", give = 4000, gem_type = 2, combinable = true, tooltip="shop_image_gems_tooltip_2"},
		[8] = {name = "shop_gem_orange_puck_2", price = {don = 10, rp = 200}, image = "images/custom_game/RDAShop/gems/yellow__2.png", rarity = "white", text_color = "white", type = "gem", give = 4000, gem_type = 3, combinable = true, tooltip="shop_image_gems_tooltip_3"},
		[9] = {name = "shop_gem_red_puck_2", price = {don = 10, rp = 200}, image = "images/custom_game/RDAShop/gems/red__2.png", rarity = "white", text_color = "white", type = "gem", give = 4000, gem_type = 4, combinable = true, tooltip="shop_image_gems_tooltip_4"},
		[10] = {name = "shop_gem_green_puck_2", price = {don = 10, rp = 200}, image = "images/custom_game/RDAShop/gems/green__2.png", rarity = "white", text_color = "white", type = "gem", give = 4000, gem_type = 5, combinable = true, tooltip="shop_image_gems_tooltip_5"},
		[11] = {name = "shop_gem_purple_puck_3", price = {don = 18, rp = 350}, image = "images/custom_game/RDAShop/gems/purple__3.png", rarity = "white", text_color = "white", type = "gem", give = 8000, gem_type = 1, combinable = true, tooltip="shop_image_gems_tooltip_1"},
		[12] = {name = "shop_gem_blue_puck_3", price = {don = 18, rp = 350}, image = "images/custom_game/RDAShop/gems/blue__3.png", rarity = "white", text_color = "white", type = "gem", give = 8000, gem_type = 2, combinable = true, tooltip="shop_image_gems_tooltip_2"},
		[13] = {name = "shop_gem_orange_puck_3", price = {don = 18, rp = 350}, image = "images/custom_game/RDAShop/gems/yellow__3.png", rarity = "white", text_color = "white", type = "gem", give = 8000, gem_type = 3, combinable = true, tooltip="shop_image_gems_tooltip_3"},
		[14] = {name = "shop_gem_red_puck_3", price = {don = 18, rp = 350}, image = "images/custom_game/RDAShop/gems/red__3.png", rarity = "white", text_color = "white", type = "gem", give = 8000, gem_type = 4, combinable = true, tooltip="shop_image_gems_tooltip_4"},
		[15] = {name = "shop_gem_green_puck_3", price = {don = 18, rp = 350}, image = "images/custom_game/RDAShop/gems/green__3.png", rarity = "white", text_color = "white", type = "gem", give = 8000, gem_type = 5, combinable = true, tooltip="shop_image_gems_tooltip_5"},
		[16] = {name = "shop_gem_purple_puck_4", price = {don = 40, rp = 600}, image = "images/custom_game/RDAShop/gems/purple__4.png", rarity = "white", text_color = "white", type = "gem", give = 20000, gem_type = 1, combinable = true, tooltip="shop_image_gems_tooltip_1"},
		[17] = {name = "shop_gem_blue_puck_4", price = {don = 40, rp = 600}, image = "images/custom_game/RDAShop/gems/blue__4.png", rarity = "white", text_color = "white", type = "gem", give = 20000, gem_type = 2, combinable = true, tooltip="shop_image_gems_tooltip_2"},
		[18] = {name = "shop_gem_orange_puck_4", price = {don = 40, rp = 600}, image = "images/custom_game/RDAShop/gems/yellow__4.png", rarity = "white", text_color = "white", type = "gem", give = 20000, gem_type = 3, combinable = true, tooltip="shop_image_gems_tooltip_3"},
		[19] = {name = "shop_gem_red_puck_4", price = {don = 40, rp = 600}, image = "images/custom_game/RDAShop/gems/red__4.png", rarity = "white", text_color = "white", type = "gem", give = 20000, gem_type = 4, combinable = true, tooltip="shop_image_gems_tooltip_4"},
		[20] = {name = "shop_gem_green_puck_4", price = {don = 40, rp = 600}, image = "images/custom_game/RDAShop/gems/green__4.png", rarity = "white", text_color = "white", type = "gem", give = 20000, gem_type = 5, combinable = true, tooltip="shop_image_gems_tooltip_5"},
	},
}