return {
	eEvents = {
		DEMO_MODE_EVENT_SELECT_HERO = 0,
		DEMO_MODE_EVENT_SELECT_ABILITY = 1,
		DEMO_MODE_EVENT_SELECT_INNATE_ABILITY = 2,
		DEMO_MODE_EVENT_ADDED_AEGIS = 3,
		DEMO_MODE_EVENT_ADDED_FREE_GOLD = 4,
		DEMO_MODE_EVENT_ADDED_FREE_SPELLS = 5,
		DEMO_MODE_EVENT_ADDED_INVULNERABLE = 6,
		DEMO_MODE_EVENT_ADDED_STRENGTH = 7,
		DEMO_MODE_EVENT_ADDED_AGILITY = 8,
		DEMO_MODE_EVENT_ADDED_INTELLECT = 9,
		DEMO_MODE_EVENT_ADDED_LEVEL = 10,
		DEMO_MODE_EVENT_SELECT_ROUND = 11,
		DEMO_MODE_EVENT_GO_TO_ROUND = 12,
		DEMO_MODE_EVENT_INCREASED_ROUND = 13,
		DEMO_MODE_EVENT_ADDED_INVULNERABLE_CREEPS = 14,
		DEMO_MODE_EVENT_PAUSED = 15,
		DEMO_MODE_EVENT_QUIT = 16,
		DEMO_MODE_EVENT_TIME_SCALE = 17,
		DEMO_MODE_EVENT_SELECT_MASTERY = 18,
		DEMO_MODE_EVENT_CLEAR_ALL_ABILITIES = 19,
		DEMO_MODE_EVENT_TOGGLE_ROUND_AUTO_START = 20,
		DEMO_MODE_EVENT_REMOVE_MASTERY = 21,
		DEMO_MODE_EVENT_SELECT_NEUTRAL_ITEM = 22,
		DEMO_MODE_EVENT_KILL_ALL = 23,
		DEMO_MODE_EVENT_ADDED_CURSE = 24,
		DEMO_MODE_EVENT_REMOVED_CURSE = 25,
		DEMO_MODE_EVENT_TOGGLE_DUELS = 26,
		DEMO_MODE_EVENT_ADD_BOT = 27,
		DEMO_MODE_EVENT_BOT_DIFFICULTY = 28,

		DEMO_MODE_EVENT_COUNT = 29,
		DEMO_MODE_EVENT_MAX = 28,
	},

	NoCopyModifiers = {
		modifier_demo_strength = true,
		modifier_demo_agility = true,
		modifier_demo_intellect = true,
	}

}
