--ITEMS CATEGORIES
CHC_ITEM_TYPE_MASTERIES				= 0
CHC_ITEM_TYPE_TREASURES				= 1
CHC_ITEM_TYPE_AURAS					= 2
CHC_ITEM_TYPE_HERO_SKINS			= 3
CHC_ITEM_TYPE_PETS					= 4
CHC_ITEM_TYPE_KILL_EFFECTS			= 5
CHC_ITEM_TYPE_BARRAGES				= 6
CHC_ITEM_TYPE_COSMETIC_ABILITIES	= 7
CHC_ITEM_TYPE_DUEL_EFFECTS			= 8
CHC_ITEM_TYPE_BET_EFFECTS			= 9
CHC_ITEM_TYPE_EFFIGIES				= 10
CHC_ITEM_TYPE_SPELL_EFFECTS			= 11
CHC_ITEM_TYPE_ITEMS					= 12
CHC_ITEM_TYPE_CHAT_WHEELS			= 13
CHC_ITEM_TYPE_INTERFACES			= 14
CHC_ITEM_TYPE_SPRAYS				= 15
CHC_ITEM_TYPE_SPECIALS				= 16

GIFT_CODE_USED = 0
GIFT_CODE_INCORRECT = 1
GIFT_CODE_ACTIVATED = 2
