require("game/filters/init")
require("game/events/init")
require("game/webapi/init")

require("game/bound_enforcer")
require("game/TestMode/index")
require("game/chat_commands")
require("game/custom_chat")
require("game/hero_builder/hero_builder")
require("game/illusions")
require("game/item_loot")
require("game/player_options")
require("game/pvp_manager/pvp_manager")
require("game/round_manager/round_manager")
require("game/summon")
require("game/game_options")
require("game/networth")
require("game/history")
require("game/party_mode")
require("game/benchmark")
require("game/dps_counter")

require("game/5v5/init")
