-- Betting base pot, according to map
BET_MANAGER_BASE_POT = {
	ffa = 1350,
	duos = 1600,
	demo = 1350,
}

-- Pvp-related modifiers
LinkLuaModifier("modifier_loser_curse", "heroes/modifier_loser_curse", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_summon_pre_duel_frozen", "creatures/abilities/modifier_summon_pre_duel_frozen", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_hero_pre_duel_frozen", "heroes/modifier_hero_pre_duel_frozen", LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_hero_pre_duel_mini_safety", "heroes/modifier_hero_pre_duel_mini_safety", LUA_MODIFIER_MOTION_NONE)

-- Pvp frequency, according to map and teams remaining
PvpManager.pvp_interval = {}
PvpManager.pvp_interval["ffa"] = {
	[10] = 1,
	[9] = 1,
	[8] = 1,
	[7] = 1,
	[6] = 2,
	[5] = 2,
	[4] = 2,
	[3] = 2,
	[2] = 3
}

PvpManager.pvp_interval["duos"] = {
	[7] = 1,
	[6] = 1,
	[5] = 1,
	[4] = 2,
	[3] = 2,
	[2] = 3
}

PvpManager.pvp_interval["demo"] = {
	[2] = 0,
	[3] = 0,
	[4] = 0,
	[5] = 0,
	[6] = 0,
	[7] = 0,
	[8] = 0,
	[9] = 0,
	[10] = 0,
}

-- Sudden death constants
PvpManager.sudden_death_start_round = 40

PvpManager.sudden_death_player_count_limit = {}
PvpManager.sudden_death_player_count_limit["ffa"] = 5
PvpManager.sudden_death_player_count_limit["demo"] = 5
PvpManager.sudden_death_player_count_limit["duos"] = 3

-- Duel win voicelines
PvpManager.winner_sound_map = {
	npc_dota_hero_abaddon =				"abaddon_abad_win_03",
	npc_dota_hero_abyssal_underlord =	"abyssal_underlord_abys_win_05",
	npc_dota_hero_alchemist =			"alchemist_alch_win_03",
	npc_dota_hero_ancient_apparition =	"ancient_apparition_appa_win_03",
	npc_dota_hero_antimage =			"antimage_anti_win_03",
	npc_dota_hero_arc_warden =			"arc_warden_arcwar_win_05",
	npc_dota_hero_axe =					"axe_axe_win_02",
	npc_dota_hero_bane =				"bane_bane_win_02",
	npc_dota_hero_batrider =			"batrider_bat_win_04",
	npc_dota_hero_beastmaster =			"beastmaster_beas_win_02",
	npc_dota_hero_bloodseeker =			"bloodseeker_blod_win_03",
	npc_dota_hero_bounty_hunter =		"bounty_hunter_bount_win_05",
	npc_dota_hero_brewmaster =			"brewmaster_brew_win_03",
	npc_dota_hero_bristleback =			"bristleback_bristle_win_04",
	npc_dota_hero_broodmother =			"broodmother_broo_win_04",
	npc_dota_hero_centaur =				"centaur_cent_win_04",
	npc_dota_hero_chaos_knight =		"chaos_knight_chaknight_win_04",
	npc_dota_hero_chen =				"chen_chen_win_02",
	npc_dota_hero_clinkz =				"clinkz_clinkz_win_03",
	npc_dota_hero_crystal_maiden =		"crystalmaiden_cm_win_04",
	npc_dota_hero_dark_seer =			"dark_seer_dkseer_win_05",
	npc_dota_hero_dark_willow =			"dark_willow_sylph_win_05",
	npc_dota_hero_dawnbreaker =			"dawnbreaker_valora_wheel_laugh_03",
	npc_dota_hero_dazzle =				"dazzle_dazz_win_03",
	npc_dota_hero_death_prophet =		"death_prophet_dpro_win_03",
	npc_dota_hero_disruptor =			"disruptor_dis_win_05",
	npc_dota_hero_doom_bringer =		"doom_bringer_doom_win_03",
	npc_dota_hero_dragon_knight =		"dragon_knight_drag_win_03",
	npc_dota_hero_drow_ranger =			"drowranger_dro_win_05",
	npc_dota_hero_earth_spirit =		"earth_spirit_earthspi_win_03",
	npc_dota_hero_earthshaker =			"earthshaker_erth_win_03",
	npc_dota_hero_elder_titan =			"elder_titan_elder_win_03",
	npc_dota_hero_ember_spirit =		"ember_spirit_embr_win_03",
	npc_dota_hero_enchantress =			"enchantress_ench_rare_02",
	npc_dota_hero_enigma =				"enigma_enig_rare_01",
	npc_dota_hero_faceless_void =		"faceless_void_face_win_03",
	npc_dota_hero_furion =				"furion_furi_view_victory_03",
	npc_dota_hero_grimstroke =			"grimstroke_grimstroke_win_04",
	npc_dota_hero_gyrocopter =			"gyrocopter_gyro_kill_04",
	npc_dota_hero_hoodwink =			"hoodwink_hoodwink_win_07",
	npc_dota_hero_huskar =				"huskar_husk_win_03",
	npc_dota_hero_invoker =				"invoker_invo_win_01",
	npc_dota_hero_jakiro =				"jakiro_jak_win_02",
	npc_dota_hero_juggernaut =			"juggernaut_jug_rare_06",
	npc_dota_hero_keeper_of_the_light =	"keeper_of_the_light_keep_win_02",
	npc_dota_hero_kunkka =				"kunkka_kunk_win_03",
	npc_dota_hero_legion_commander =	"legion_commander_legcom_win_03",
	npc_dota_hero_leshrac =				"leshrac_lesh_rare_01",
	npc_dota_hero_lich =				"lich_lich_rare_01",
	npc_dota_hero_life_stealer =		"life_stealer_lifest_win_03",
	npc_dota_hero_lina =				"lina_lina_win_03",
	npc_dota_hero_lion =				"lion_lion_kill_06",
	npc_dota_hero_lone_druid =			"lone_druid_lone_druid_win_03",
	npc_dota_hero_luna =				"luna_luna_win_03",
	npc_dota_hero_lycan =				"lycan_lycan_respawn_06",
	npc_dota_hero_magnataur =			"magnataur_magn_win_01",
	npc_dota_hero_marci =				"marci_marci_laugh",
	npc_dota_hero_mars =				"mars_mars_win_02 ",
	npc_dota_hero_medusa =				"medusa_medus_win_05",
	npc_dota_hero_meepo =				"meepo_meepo_win_04",
	npc_dota_hero_mirana =				"mirana_mir_rare_09",
	npc_dota_hero_monkey_king =			"monkey_king_monkey_win_01",
	npc_dota_hero_morphling =			"morphling_mrph_win_03",
	npc_dota_hero_naga_siren =			"naga_siren_naga_win_03",
	npc_dota_hero_necrolyte =			"necrolyte_necr_respawn_13",
	npc_dota_hero_nevermore =			"nevermore_nev_win_03",
	npc_dota_hero_night_stalker =		"night_stalker_nstalk_win_01",
	npc_dota_hero_nyx_assassin =		"nyx_assassin_nyx_win_04",
	npc_dota_hero_obsidian_destroyer =	"outworld_destroyer_odest_win_04",
	npc_dota_hero_ogre_magi =			"ogre_magi_ogmag_win_03",
	npc_dota_hero_omniknight =			"omniknight_omni_win_03",
	npc_dota_hero_oracle =				"oracle_orac_win_01",
	npc_dota_hero_pangolier =			"pangolin_pangolin_win_02",
	npc_dota_hero_phantom_assassin =	"phantom_assassin_phass_win_02",
	npc_dota_hero_phantom_lancer =		"phantom_lancer_plance_kill_10",
	npc_dota_hero_phoenix =				"phoenix_phoenix_bird_victory",
	npc_dota_hero_puck =				"puck_puck_win_04",
	npc_dota_hero_pudge =				"pudge_pud_rare_05",
	npc_dota_hero_pugna =				"pugna_pugna_win_03",
	npc_dota_hero_queenofpain =			"queenofpain_pain_win_03",
	npc_dota_hero_rattletrap =			"rattletrap_ratt_win_04",
	npc_dota_hero_razor =				"razor_raz_level_04",
	npc_dota_hero_riki =				"riki_riki_level_05",
	npc_dota_hero_rubick =				"rubick_rubick_win_03",
	npc_dota_hero_sand_king =			"sandking_skg_level_02",
	npc_dota_hero_shadow_demon =		"shadow_demon_shadow_demon_win_03",
	npc_dota_hero_shadow_shaman =		"shadowshaman_shad_win_03",
	npc_dota_hero_snapfire =			"snapfire_snapfire_win_01 ",
	npc_dota_hero_shredder =			"shredder_timb_levelup_07",
	npc_dota_hero_silencer =			"silencer_silen_win_03",
	npc_dota_hero_skeleton_king =		"skeleton_king_wraith_level_07",
	npc_dota_hero_skywrath_mage =		"skywrath_mage_drag_levelup_02",
	npc_dota_hero_slardar =				"slardar_slar_win_05",
	npc_dota_hero_slark =				"slark_slark_win_03",
	npc_dota_hero_sniper =				"sniper_snip_rare_01",
	npc_dota_hero_spectre =				"spectre_spec_win_01",
	npc_dota_hero_spirit_breaker =		"spirit_breaker_spir_win_03",
	npc_dota_hero_storm_spirit =		"stormspirit_ss_win_03",
	npc_dota_hero_sven =				"sven_sven_win_05",
	npc_dota_hero_techies =				"techies_tech_move_52",
	npc_dota_hero_templar_assassin =	"templar_assassin_temp_win_03",
	npc_dota_hero_terrorblade =			"terrorblade_terr_shards_win_03",
	npc_dota_hero_tidehunter =			"tidehunter_tide_rare_01",
	npc_dota_hero_tinker =				"tinker_tink_win_03",
	npc_dota_hero_tiny =				"tiny_tiny_win_02",
	npc_dota_hero_treant =				"treant_treant_win_04",
	npc_dota_hero_troll_warlord =		"troll_warlord_troll_win_03",
	npc_dota_hero_tusk =				"tusk_tusk_win_01",
	npc_dota_hero_undying =				"undying_undying_win_05",
	npc_dota_hero_ursa =				"ursa_ursa_win_02",
	npc_dota_hero_vengefulspirit =		"vengefulspirit_vng_win_02",
	npc_dota_hero_venomancer =			"venomancer_venm_win_03",
	npc_dota_hero_viper =				"viper_vipe_win_02",
	npc_dota_hero_visage =				"visage_visa_win_03",
	npc_dota_hero_void_spirit =			"void_spirit_voidspir_win_01",
	npc_dota_hero_warlock =				"warlock_warl_win_04",
	npc_dota_hero_weaver =				"weaver_weav_win_03",
	npc_dota_hero_windrunner =			"windrunner_wind_win_04",
	npc_dota_hero_winter_wyvern =		"winter_wyvern_winwyv_win_02",
	npc_dota_hero_wisp =				"wisp_win",
	npc_dota_hero_witch_doctor =		"witchdoctor_wdoc_win_04",
	npc_dota_hero_zuus =				"zuus_zuus_rare_03",
}
