require("game/webapi/webapi")
require("game/webapi/error_tracking")
require("game/webapi/match_events")
require("game/webapi/payments")
require("game/webapi/supporters")
require("game/webapi/feedback")
require("game/webapi/patchnotes")
require("game/webapi/synced_chat")

require("game/battlepass/core")
