require("extensions/table")
require("extensions/string")
require("extensions/cdota_buff")
require("extensions/cdota_base_npc")
require("extensions/cdota_base_ability")
require("extensions/cdotaplayercontroller")
require("extensions/cdota_modifier_lua")
